// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTzt_2Yl7M4xuAKg1CNkf8OICu1U1oe1M',
    appId: '1:908693072368:web:35f508560bc70586589535',
    messagingSenderId: '908693072368',
    projectId: 'fruitclassifierelbakay',
    authDomain: 'fruitclassifierelbakay.firebaseapp.com',
    storageBucket: 'fruitclassifierelbakay.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvguJOwCFSW-P8soprACUgPiIbqUdRn88',
    appId: '1:908693072368:android:b8cccfeedbead236589535',
    messagingSenderId: '908693072368',
    projectId: 'fruitclassifierelbakay',
    storageBucket: 'fruitclassifierelbakay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD46p3IUPBP9NiD6Z8W90Hs5HfIMCcX99E',
    appId: '1:908693072368:ios:bf5b9eafdce6ccf8589535',
    messagingSenderId: '908693072368',
    projectId: 'fruitclassifierelbakay',
    storageBucket: 'fruitclassifierelbakay.firebasestorage.app',
    iosBundleId: 'come.bky.smartAppElbakayG8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD46p3IUPBP9NiD6Z8W90Hs5HfIMCcX99E',
    appId: '1:908693072368:ios:bf5b9eafdce6ccf8589535',
    messagingSenderId: '908693072368',
    projectId: 'fruitclassifierelbakay',
    storageBucket: 'fruitclassifierelbakay.firebasestorage.app',
    iosBundleId: 'come.bky.smartAppElbakayG8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTzt_2Yl7M4xuAKg1CNkf8OICu1U1oe1M',
    appId: '1:908693072368:web:babd04a5ad4e851f589535',
    messagingSenderId: '908693072368',
    projectId: 'fruitclassifierelbakay',
    authDomain: 'fruitclassifierelbakay.firebaseapp.com',
    storageBucket: 'fruitclassifierelbakay.firebasestorage.app',
  );
}
